/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FnbDao;
import javax.swing.JOptionPane;
import view.MainMenu;

/**
 *
 * @author binta
 */
public class FnB extends javax.swing.JFrame {

    /**
     * Creates new form FnB
     */
    public FnB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tempatsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempatharga = new javax.swing.JTextField();
        tempatnama = new javax.swing.JTextField();
        tempatid = new javax.swing.JTextField();
        tempatvendor = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        view = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(255, 127, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Refresh");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 127, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Refresh");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(549, 525));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 387, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_item", "nama_item", "harga", "id_vendor"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 463, 185));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 127, 0));
        jLabel2.setText("DATA FNB");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 29, -1, -1));

        tempatsearch.setBackground(new java.awt.Color(204, 204, 204));
        tempatsearch.setForeground(new java.awt.Color(0, 0, 0));
        tempatsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatsearchActionPerformed(evt);
            }
        });
        jPanel2.add(tempatsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 60, 177, -1));

        search.setBackground(new java.awt.Color(255, 127, 0));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorderPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 60, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Search");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 63, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tabel FnB");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 95, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Form Input FnB");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 315, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("id_item");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 340, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("nama_item");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 368, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("harga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 398, -1, -1));

        tempatharga.setBackground(new java.awt.Color(204, 204, 204));
        tempatharga.setForeground(new java.awt.Color(0, 0, 0));
        tempatharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempathargaActionPerformed(evt);
            }
        });
        jPanel2.add(tempatharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 395, 177, -1));

        tempatnama.setBackground(new java.awt.Color(204, 204, 204));
        tempatnama.setForeground(new java.awt.Color(0, 0, 0));
        tempatnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatnamaActionPerformed(evt);
            }
        });
        jPanel2.add(tempatnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 365, 177, -1));

        tempatid.setBackground(new java.awt.Color(204, 204, 204));
        tempatid.setForeground(new java.awt.Color(0, 0, 0));
        tempatid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatidActionPerformed(evt);
            }
        });
        jPanel2.add(tempatid, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 337, 177, -1));

        tempatvendor.setBackground(new java.awt.Color(204, 204, 204));
        tempatvendor.setForeground(new java.awt.Color(0, 0, 0));
        tempatvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatvendorActionPerformed(evt);
            }
        });
        jPanel2.add(tempatvendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 423, 177, -1));

        insert.setBackground(new java.awt.Color(76, 175, 80));
        insert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Insert");
        insert.setBorderPainted(false);
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel2.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 457, -1, -1));

        update.setBackground(new java.awt.Color(255, 215, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 457, -1, -1));

        delete.setBackground(new java.awt.Color(255, 127, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 457, -1, -1));

        clear.setBackground(new java.awt.Color(0, 191, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorderPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 457, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Kembali");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 496, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("id_vendor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 426, -1, -1));

        view.setBackground(new java.awt.Color(255, 127, 0));
        view.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.setBorderPainted(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempatsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatsearchActionPerformed

    private void tempathargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempathargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempathargaActionPerformed

    private void tempatnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatnamaActionPerformed

    private void tempatidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatidActionPerformed

    private void tempatvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatvendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatvendorActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String idItem = tempatid.getText();
        String namaItem = tempatnama.getText();
        String hargaString = tempatharga.getText();
        String idVendor = tempatvendor.getText();

    // 2. Validasi (ID tidak boleh kosong karena itu kuncinya)
    if (idItem.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit atau isi ID!");
        return;
    }

    try {
        java.math.BigDecimal harga = new java.math.BigDecimal(hargaString);

        model.FnB fnbUpdate = new model.FnB();
        fnbUpdate.setIdItem(idItem);
        fnbUpdate.setNamaItem(namaItem);
        fnbUpdate.setHarga(harga);
        fnbUpdate.setIdVendor(idVendor);

        dao.FnbDao dao = new dao.FnbDao();
        
        // 3. Panggil method UPDATE
        boolean sukses = dao.update(fnbUpdate);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
            tampilkanData(); // Refresh tabel
            
            // Bersihkan form
            tempatid.setText("");
            tempatnama.setText("");
            tempatharga.setText("");
            tempatvendor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Mengupdate Data.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Harga harus angka!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String idItem = tempatid.getText();

    // 1. Validasi ID
    if (idItem.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus atau isi ID!");
        return;
    }

    // 2. Konfirmasi User (Yes/No)
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data ID: " + idItem + "?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        dao.FnbDao dao = new dao.FnbDao();
        
        // 3. Panggil method DELETE
        boolean sukses = dao.delete(idItem);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
            tampilkanData(); // Refresh tabel
            
            // Bersihkan form
            tempatid.setText("");
            tempatnama.setText("");
            tempatharga.setText("");
            tempatvendor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menghapus Data.");
        }
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        tempatid.setText("");
        tempatnama.setText("");
        tempatharga.setText("");
        tempatvendor.setText("");

        // Opsional: Kembalikan tabel ke posisi default (load semua data)
        tampilkanData(); 
        tempatid.requestFocus(); // Arahkan kursor kembali ke kolom ID
    }//GEN-LAST:event_clearActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MainMenu mnu = new MainMenu();
        mnu.setVisible(true);

        // TUTUP Vendor
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

    String keyword = tempatsearch.getText(); 

    dao.FnbDao dao = new dao.FnbDao();
    
    // Panggil method SEARCH dari DAO
    java.util.List<model.FnB> hasilPencarian = dao.searchByName(keyword);

    // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Kosongkan tabel dulu

    if (hasilPencarian.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
    } else {
        for (model.FnB f : hasilPencarian) {
            Object[] baris = {
                f.getIdItem(),
                f.getNamaItem(),
                f.getHarga(),
                f.getIdVendor()
            };
            model.addRow(baris);
        }
    }
    }//GEN-LAST:event_searchActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // 1. Ambil data dari Inputan (Text Field)
    String idItem = tempatid.getText();
    String namaItem = tempatnama.getText();
    String hargaString = tempatharga.getText();
    String idVendor = tempatvendor.getText();

    // 2. Validasi sederhana (Cek kosong atau tidak)
    if (idItem.isEmpty() || namaItem.isEmpty() || hargaString.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!");
        return; // Berhenti jika data kosong
    }

    try {
        // 3. Konversi Harga dari String ke BigDecimal
        // (Wajib karena di database tipe datanya Decimal/BigDecimal)
        java.math.BigDecimal harga = new java.math.BigDecimal(hargaString);

        // 4. Masukkan data ke dalam Object Model (FnB)
        model.FnB fnbBaru = new model.FnB();
        fnbBaru.setIdItem(idItem);
        fnbBaru.setNamaItem(namaItem);
        fnbBaru.setHarga(harga);
        fnbBaru.setIdVendor(idVendor);

        // 5. Panggil DAO untuk Insert
        FnbDao dao = new FnbDao(); // Pastikan constructor FnbDao sudah diperbaiki (lihat poin 1)
        boolean sukses = dao.insert(fnbBaru);

        // 6. Cek Hasil dan Beri Pesan ke User
        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            
            tampilkanData();
            
            // Opsi: Kosongkan text field setelah simpan
            tempatid.setText("");
            tempatnama.setText("");
            tempatharga.setText("");
            tempatvendor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data.");
        }

    } catch (NumberFormatException e) {
        // Error handling jika user memasukkan huruf di kolom harga
        javax.swing.JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
    }
    }//GEN-LAST:event_insertActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       tampilkanData();
    }//GEN-LAST:event_viewActionPerformed

    private void tampilkanData() {
    // 1. Siapkan Model Tabel
    // Pastikan nama variabel tabelmu sesuai (misal: jTable1 atau tblData)
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // 2. Kosongkan tabel dulu agar tidak dobel saat direfresh
    model.setRowCount(0);

    // 3. Ambil data dari Database pakai DAO
    dao.FnbDao dao = new dao.FnbDao();
    java.util.List<model.FnB> listFnb = dao.getAll();

    // 4. Masukkan data ke Tabel
    for (model.FnB f : listFnb) {
        Object[] baris = {
            f.getIdItem(),
            f.getNamaItem(),
            f.getHarga(),
            f.getIdVendor()
            // Tambahkan nama vendor jika ada di model
        };
        model.addRow(baris);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FnB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FnB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FnB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FnB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FnB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField tempatharga;
    private javax.swing.JTextField tempatid;
    private javax.swing.JTextField tempatnama;
    private javax.swing.JTextField tempatsearch;
    private javax.swing.JTextField tempatvendor;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}