/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.KasirDao;

/**
 *
 * @author trila
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelkasir = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tempatsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tempatnama = new javax.swing.JTextField();
        tempatid = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(549, 525));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tabelkasir.setBackground(new java.awt.Color(255, 255, 255));
        tabelkasir.setForeground(new java.awt.Color(0, 0, 0));
        tabelkasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id_kasir", "nama_kasir"
            }
        ));
        tabelkasir.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tabelkasir);

        jScrollPane3.setViewportView(jScrollPane4);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 147, -1, 173));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 191, 255));
        jLabel9.setText("DATA KASIR");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        tempatsearch.setBackground(new java.awt.Color(204, 204, 204));
        tempatsearch.setForeground(new java.awt.Color(0, 0, 0));
        tempatsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatsearchActionPerformed(evt);
            }
        });
        jPanel3.add(tempatsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 72, 177, -1));

        search.setBackground(new java.awt.Color(0, 191, 255));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorderPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 72, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Search");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 75, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tabel Kasir");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 119, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Form Input Kasir");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("id_kasir");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("nama_kasir");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 20));

        tempatnama.setBackground(new java.awt.Color(204, 204, 204));
        tempatnama.setForeground(new java.awt.Color(0, 0, 0));
        tempatnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatnamaActionPerformed(evt);
            }
        });
        jPanel3.add(tempatnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 177, -1));

        tempatid.setBackground(new java.awt.Color(204, 204, 204));
        tempatid.setForeground(new java.awt.Color(0, 0, 0));
        tempatid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatidActionPerformed(evt);
            }
        });
        jPanel3.add(tempatid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 177, -1));

        tambah.setBackground(new java.awt.Color(76, 175, 80));
        tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("Insert");
        tambah.setBorderPainted(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel3.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 460, -1, -1));

        update.setBackground(new java.awt.Color(255, 215, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 460, -1, -1));

        delete.setBackground(new java.awt.Color(255, 127, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 460, -1, -1));

        clear.setBackground(new java.awt.Color(0, 191, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorderPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 460, -1, -1));

        kembali.setBackground(new java.awt.Color(204, 204, 204));
        kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembali.setForeground(new java.awt.Color(0, 0, 0));
        kembali.setText("Kembali");
        kembali.setBorderPainted(false);
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel3.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        view.setBackground(new java.awt.Color(0, 191, 255));
        view.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.setBorderPainted(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel3.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 72, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempatsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatsearchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    String keyword = tempatsearch.getText(); 

    dao.KasirDao dao = new dao.KasirDao();
    
    // Panggil method SEARCH dari DAO
    java.util.List<model.Kasir> hasilPencarian = dao.searchByName(keyword);

    // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelkasir.getModel();
    model.setRowCount(0); // Kosongkan tabel dulu

    if (hasilPencarian.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
    } else {
        for (model.Kasir f : hasilPencarian) {
            Object[] baris = {
                f.getIdKasir(),
                f.getNamaKasir(),
            };
            model.addRow(baris);
        }
    }
    }//GEN-LAST:event_searchActionPerformed

    private void tempatnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatnamaActionPerformed

    private void tempatidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatidActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // 1. Ambil data dari Inputan (Text Field)
        String idKasir = tempatid.getText();
        String namaKasir = tempatnama.getText();

    // 2. Validasi sederhana (Cek kosong atau tidak)
    if (idKasir.isEmpty() || namaKasir.isEmpty() ) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!");
        return; // Berhenti jika data kosong
    }

    try {
        model.Kasir ksr = new model.Kasir();
        ksr.setIdKasir(idKasir);
        ksr.setNamaKasir(namaKasir);
        
        //Panggil DAO untuk Insert
        KasirDao dao = new KasirDao(); // Pastikan constructor FnbDao sudah diperbaiki (lihat poin 1)
        boolean sukses = dao.insert(ksr);

        // 6. Cek Hasil dan Beri Pesan ke User
        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            
            tampilkanData();
            
            // Opsi: Kosongkan text field setelah simpan
            tempatid.setText("");
            tempatnama.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data.");
        }

    } catch (NumberFormatException e) {
        // Error handling jika user memasukkan huruf di kolom harga
        javax.swing.JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Error: " + e.getMessage());
    }
    }//GEN-LAST:event_tambahActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String idKasir = tempatid.getText();
        String namaKasir = tempatnama.getText();

    // 2. Validasi (ID tidak boleh kosong karena itu kuncinya)
    if (idKasir.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit atau isi ID!");
        return;
    }

    try {

        model.Kasir kas = new model.Kasir();
        kas.setIdKasir(idKasir);
        kas.setNamaKasir(namaKasir);

        dao.KasirDao dao = new dao.KasirDao();
        
        // 3. Panggil method UPDATE
        boolean sukses = dao.update(kas);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
            tampilkanData(); // Refresh tabel
            
            // Bersihkan form
            tempatid.setText("");
            tempatnama.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Mengupdate Data.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Harga harus angka!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String idKasir = tempatid.getText();

    // 1. Validasi ID
    if (idKasir.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus atau isi ID!");
        return;
    }

    // 2. Konfirmasi User (Yes/No)
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data ID: " + idKasir + "?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        dao.KasirDao dao = new dao.KasirDao();
        
        // 3. Panggil method DELETE
        boolean sukses = dao.delete(idKasir);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
            tampilkanData(); // Refresh tabel
            
            // Bersihkan form
            tempatid.setText("");
            tempatnama.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menghapus Data.");
        }
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void tampilkanData() {
    // 1. Siapkan Model Tabel
    // Pastikan nama variabel tabelmu sesuai (misal: jTable1 atau tblData)
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelkasir.getModel();
    
    // 2. Kosongkan tabel dulu agar tidak dobel saat direfresh
    model.setRowCount(0);

    // 3. Ambil data dari Database pakai DAO
    dao.KasirDao dao = new dao.KasirDao();
    java.util.List<model.Kasir> listKasir = dao.getAll();

    // 4. Masukkan data ke Tabel
    for (model.Kasir f : listKasir) {
        Object[] baris = {
            f.getIdKasir(),
            f.getNamaKasir(),
            // Tambahkan nama vendor jika ada di model
        };
        model.addRow(baris);
    }
}
    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        tempatid.setText("");
        tempatnama.setText("");

        // Opsional: Kembalikan tabel ke posisi default (load semua data)
        //tampilkanData();
        tempatid.requestFocus(); // Arahkan kursor kembali ke kolom ID
    }//GEN-LAST:event_clearActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        MainMenu mnu = new MainMenu();
        mnu.setVisible(true);

        // TUTUP Vendor
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       tampilkanData();
    }//GEN-LAST:event_viewActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton kembali;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelkasir;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tempatid;
    private javax.swing.JTextField tempatnama;
    private javax.swing.JTextField tempatsearch;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
