/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author binta
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tomboltransaksi = new javax.swing.JButton();
        laporanharian = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fnb = new javax.swing.JButton();
        tombolvendor = new javax.swing.JButton();
        rombolruangan = new javax.swing.JButton();
        tombolpelanggan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 127, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/online-payment_2146259.png"))); // NOI18N
        jButton2.setText("Pembayaran");
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 280, 230, 80);

        jButton3.setBackground(new java.awt.Color(0, 191, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cashier_2681665.png"))); // NOI18N
        jButton3.setText("Daftar Kasir");
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(280, 280, 234, 80);

        tomboltransaksi.setBackground(new java.awt.Color(76, 175, 80));
        tomboltransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tomboltransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tomboltransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cash-register_4437664 (1).png"))); // NOI18N
        tomboltransaksi.setText("Transaksi");
        tomboltransaksi.setAlignmentX(0.5F);
        tomboltransaksi.setBorderPainted(false);
        tomboltransaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tomboltransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(tomboltransaksi);
        tomboltransaksi.setBounds(30, 380, 230, 80);

        laporanharian.setBackground(new java.awt.Color(255, 215, 0));
        laporanharian.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        laporanharian.setForeground(new java.awt.Color(255, 255, 255));
        laporanharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/financial-report_10815199.png"))); // NOI18N
        laporanharian.setText("Laporan Harian");
        laporanharian.setBorderPainted(false);
        laporanharian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        laporanharian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanharianActionPerformed(evt);
            }
        });
        jPanel2.add(laporanharian);
        laporanharian.setBounds(280, 380, 234, 80);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 170, 0));
        jLabel3.setText("DAGO CREATIVE HUB & CO-WORKING SPACE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 30, 350, 21);

        fnb.setBackground(new java.awt.Color(255, 127, 0));
        fnb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnb.setForeground(new java.awt.Color(255, 255, 255));
        fnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/food_15257547.png"))); // NOI18N
        fnb.setText("FnB");
        fnb.setAlignmentX(0.5F);
        fnb.setBorderPainted(false);
        fnb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnbActionPerformed(evt);
            }
        });
        jPanel2.add(fnb);
        fnb.setBounds(30, 80, 230, 80);

        tombolvendor.setBackground(new java.awt.Color(0, 191, 255));
        tombolvendor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolvendor.setForeground(new java.awt.Color(255, 255, 255));
        tombolvendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/food_16217476.png"))); // NOI18N
        tombolvendor.setText("Vendor");
        tombolvendor.setBorderPainted(false);
        tombolvendor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tombolvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolvendorActionPerformed(evt);
            }
        });
        jPanel2.add(tombolvendor);
        tombolvendor.setBounds(280, 80, 234, 80);

        rombolruangan.setBackground(new java.awt.Color(76, 175, 80));
        rombolruangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rombolruangan.setForeground(new java.awt.Color(255, 255, 255));
        rombolruangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/home-office_2904550.png"))); // NOI18N
        rombolruangan.setText("Ruangan");
        rombolruangan.setAlignmentX(0.5F);
        rombolruangan.setBorderPainted(false);
        rombolruangan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rombolruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rombolruanganActionPerformed(evt);
            }
        });
        jPanel2.add(rombolruangan);
        rombolruangan.setBounds(30, 180, 230, 80);

        tombolpelanggan.setBackground(new java.awt.Color(255, 215, 0));
        tombolpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolpelanggan.setForeground(new java.awt.Color(255, 255, 255));
        tombolpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ancestors_3597742.png"))); // NOI18N
        tombolpelanggan.setText("Pelanggan");
        tombolpelanggan.setBorderPainted(false);
        tombolpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tombolpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolpelangganActionPerformed(evt);
            }
        });
        jPanel2.add(tombolpelanggan);
        tombolpelanggan.setBounds(280, 180, 234, 80);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/WhatsApp Image 2025-12-07 at 21.49.59_fc38cdff.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 170, 0));
        jLabel2.setText("Jl. Teleng - Singaraja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pembayaran bayar = new Pembayaran();
        bayar.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tomboltransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltransaksiActionPerformed
        Transaksi trs = new Transaksi();
        trs.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_tomboltransaksiActionPerformed

    private void fnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnbActionPerformed
       FnB fnb = new FnB();
        fnb.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_fnbActionPerformed

    private void tombolvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolvendorActionPerformed
       Vendor vnd = new Vendor();
        vnd.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_tombolvendorActionPerformed

    private void rombolruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rombolruanganActionPerformed
        Ruangan ruang = new Ruangan();
        ruang.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_rombolruanganActionPerformed

    private void tombolpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolpelangganActionPerformed
       Pelanggan plg = new Pelanggan();
        plg.setVisible(true);

        // TUTUP Menu
        this.dispose();
    }//GEN-LAST:event_tombolpelangganActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Kasir ksr = new Kasir();
        ksr.setVisible(true);

        // TUTUP LOGIN
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void laporanharianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanharianActionPerformed
        LaporanHarian lp = new LaporanHarian();
        lp.setVisible(true);

        // TUTUP LOGIN
        this.dispose();
    }//GEN-LAST:event_laporanharianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fnb;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton laporanharian;
    private javax.swing.JButton rombolruangan;
    private javax.swing.JButton tombolpelanggan;
    private javax.swing.JButton tomboltransaksi;
    private javax.swing.JButton tombolvendor;
    // End of variables declaration//GEN-END:variables
}
