package view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import dao.FNPerhitunganDao;
import dao.PelangganDao;
import dao.TransaksiFnbDao;
import dao.TransaksiRuanganDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DatabaseConnection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Time;

/**
 *
 * @author trila
 */
public class Transaksi extends javax.swing.JFrame {
    private DefaultTableModel modelRekapRuangan;
    private DefaultTableModel modelRekapFnb;
    /**
     * Creates new form transaksi
     */
    public Transaksi() {
    initComponents();      // ← ini WAJIB paling atas
    initRekapTable();      // ← ini untuk set table jadi kosong

    // Ambil model dari JTable GUI
    modelRekapRuangan = (DefaultTableModel) rekapruangan.getModel();
    modelRekapFnb     = (DefaultTableModel) rekapfnb.getModel();

    // Load dropdown
    loadComboKasir();
    loadComboPembayaran();
    }

private void initRekapTable() {
        // kalau ingin kosongkan table dulu
        rekapruangan.setModel(new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Id Ruangan","Ruangan","Waktu Mulai","Waktu Selesai", "Durasi", "Subtotal"} 
        ));
        rekapfnb.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Id Item","Item", "Qty","Subtotal"}
        ));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        view = new javax.swing.JButton();
        search2 = new javax.swing.JButton();
        view2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ttgl = new com.toedter.calendar.JDateChooser();
        tnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ttelp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tidtrans = new javax.swing.JTextField();
        token = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wmulai = new javax.swing.JTextField();
        wselesai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelfnb = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        tptqty = new javax.swing.JTextField();
        tempatsearch = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelruangan = new javax.swing.JTable();
        search3 = new javax.swing.JButton();
        view3 = new javax.swing.JButton();
        tempatsearch1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        addfnb = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpttotal = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        pmbyrn = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        tempatbayar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        kembalian = new javax.swing.JTextArea();
        hitungsusuk = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        rekapfnb = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        rekapruangan = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        proses = new javax.swing.JButton();
        kasircom = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        search.setBackground(new java.awt.Color(255, 127, 0));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorderPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(255, 127, 0));
        view.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.setBorderPainted(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        search2.setBackground(new java.awt.Color(0, 191, 255));
        search2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search2.setForeground(new java.awt.Color(255, 255, 255));
        search2.setText("Search");
        search2.setBorderPainted(false);
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });

        view2.setBackground(new java.awt.Color(0, 191, 255));
        view2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view2.setForeground(new java.awt.Color(255, 255, 255));
        view2.setText("View");
        view2.setBorderPainted(false);
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 170, 0));
        jLabel3.setText("DAGO CREATIVE HUB & CO-WORKING SPACE");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jl. Teleng-Singaraja");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nama Pelanggan");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kasir");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tanggal");

        ttgl.setBackground(new java.awt.Color(204, 204, 204));

        tnama.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telepon");

        ttelp.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID Transaksi");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Token Wi-Fi");

        tidtrans.setBackground(new java.awt.Color(204, 204, 204));

        token.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Pilih Ruangan");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Waktu Mulai");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Waktu Selesai");

        wmulai.setBackground(new java.awt.Color(204, 204, 204));

        wselesai.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Pilih FnB");

        tabelfnb.setBackground(new java.awt.Color(255, 255, 255));
        tabelfnb.setForeground(new java.awt.Color(0, 0, 0));
        tabelfnb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_item", "nama_item", "harga", "id_vendor"
            }
        ));
        tabelfnb.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabelfnb);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Qty");

        tptqty.setBackground(new java.awt.Color(204, 204, 204));

        tempatsearch.setBackground(new java.awt.Color(204, 204, 204));
        tempatsearch.setForeground(new java.awt.Color(0, 0, 0));
        tempatsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatsearchActionPerformed(evt);
            }
        });

        search1.setBackground(new java.awt.Color(255, 127, 0));
        search1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setText("Search");
        search1.setBorderPainted(false);
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        view1.setBackground(new java.awt.Color(255, 127, 0));
        view1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view1.setForeground(new java.awt.Color(255, 255, 255));
        view1.setText("View");
        view1.setBorderPainted(false);
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        tabelruangan.setBackground(new java.awt.Color(255, 255, 255));
        tabelruangan.setForeground(new java.awt.Color(0, 0, 0));
        tabelruangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_ruangan", "nama_ruangan", "harga_per_jam"
            }
        ));
        tabelruangan.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tabelruangan);

        search3.setBackground(new java.awt.Color(0, 191, 255));
        search3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search3.setForeground(new java.awt.Color(255, 255, 255));
        search3.setText("Search");
        search3.setBorderPainted(false);
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });

        view3.setBackground(new java.awt.Color(0, 191, 255));
        view3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view3.setForeground(new java.awt.Color(255, 255, 255));
        view3.setText("View");
        view3.setBorderPainted(false);
        view3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view3ActionPerformed(evt);
            }
        });

        tempatsearch1.setBackground(new java.awt.Color(204, 204, 204));
        tempatsearch1.setForeground(new java.awt.Color(0, 0, 0));
        tempatsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatsearch1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 170, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addfnb.setBackground(new java.awt.Color(0, 170, 0));
        addfnb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addfnb.setForeground(new java.awt.Color(255, 255, 255));
        addfnb.setText("Add");
        addfnb.setBorderPainted(false);
        addfnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfnbActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/WhatsApp Image 2025-12-09 at 21.41.13_85d3c52b.jpg"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Total");

        tpttotal.setBackground(new java.awt.Color(255, 255, 255));
        tpttotal.setColumns(20);
        tpttotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tpttotal.setForeground(new java.awt.Color(0, 0, 0));
        tpttotal.setRows(5);
        jScrollPane2.setViewportView(tpttotal);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Metode Pembayaran");

        pmbyrn.setBackground(new java.awt.Color(255, 255, 255));
        pmbyrn.setForeground(new java.awt.Color(0, 0, 0));
        pmbyrn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Bayar");

        tempatbayar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Kembali");

        kembalian.setBackground(new java.awt.Color(255, 255, 255));
        kembalian.setColumns(20);
        kembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembalian.setForeground(new java.awt.Color(0, 0, 0));
        kembalian.setRows(5);
        jScrollPane3.setViewportView(kembalian);

        hitungsusuk.setBackground(new java.awt.Color(153, 0, 0));
        hitungsusuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hitungsusuk.setForeground(new java.awt.Color(255, 255, 255));
        hitungsusuk.setText("Hitung Kembali");
        hitungsusuk.setBorderPainted(false);
        hitungsusuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungsusukActionPerformed(evt);
            }
        });

        rekapfnb.setBackground(new java.awt.Color(255, 255, 255));
        rekapfnb.setForeground(new java.awt.Color(0, 0, 0));
        rekapfnb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_item", "item", "qty", "subtotal"
            }
        ));
        rekapfnb.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(rekapfnb);

        rekapruangan.setBackground(new java.awt.Color(255, 255, 255));
        rekapruangan.setForeground(new java.awt.Color(0, 0, 0));
        rekapruangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Ruangan", "Ruangan", "Waktu Mulai", "Waktu Selesai", "Durasi", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rekapruangan.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(rekapruangan);

        proses.setBackground(new java.awt.Color(153, 0, 0));
        proses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proses.setForeground(new java.awt.Color(255, 255, 255));
        proses.setText("Proses");
        proses.setBorderPainted(false);
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        kasircom.setBackground(new java.awt.Color(255, 255, 255));
        kasircom.setForeground(new java.awt.Color(0, 0, 0));
        kasircom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Kembali");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("REKAP PESANAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jButton8))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttelp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153)
                        .addComponent(jLabel14)
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tidtrans)
                            .addComponent(token)
                            .addComponent(kasircom, 0, 183, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(53, 53, 53)
                                .addComponent(tempatsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search3)
                                .addGap(6, 6, 6)
                                .addComponent(view3)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel12)
                                .addGap(53, 53, 53)
                                .addComponent(tempatsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(search1)
                                .addGap(6, 6, 6)
                                .addComponent(view1))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(pmbyrn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempatbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(hitungsusuk)))))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel18)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wmulai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wselesai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)
                                                .addComponent(jButton2)))
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tptqty, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(270, 270, 270)
                                        .addComponent(addfnb))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(proses)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton6)))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(439, 439, 439))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton8))
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ttelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(token, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kasircom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(tempatsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search3)
                    .addComponent(view3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12))
                    .addComponent(tempatsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search1)
                    .addComponent(view1))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wmulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wselesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addfnb)
                    .addComponent(tptqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addComponent(jButton2))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(pmbyrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(tempatbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hitungsusuk))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proses)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadComboKasir() {
    try (Connection conn = DatabaseConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery("SELECT id_kasir, nama_kasir FROM tabel_kasir")) {
        kasircom.removeAllItems();
        while (rs.next()) {
            kasircom.addItem(rs.getString("id_kasir") + " - " + rs.getString("nama_kasir"));
        }
    } catch (Exception e) { e.printStackTrace(); }
}
private void loadComboPembayaran() {
    try (Connection conn = DatabaseConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery("SELECT id_pembayaran, jenis_pembayaran FROM tabel_pembayaran")) {
        pmbyrn.removeAllItems();
        while (rs.next()) {
            pmbyrn.addItem(rs.getString("id_pembayaran") + " - " + rs.getString("jenis_pembayaran"));
        }
    } catch (Exception e) { e.printStackTrace(); }
}


    private void updateTotal() {
    double total = 0;
    for (int i=0;i<modelRekapRuangan.getRowCount();i++) {
        total += Double.parseDouble(modelRekapRuangan.getValueAt(i, 5).toString());
    }
    for (int i=0;i<modelRekapFnb.getRowCount();i++) {
        total += Double.parseDouble(modelRekapFnb.getValueAt(i, 3).toString());
    }
    tpttotal.setText(String.format("Rp %.0f", total)); // round as desired
}
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String keyword = tempatsearch.getText();

        dao.FnbDao dao = new dao.FnbDao();

        // Panggil method SEARCH dari DAO
        java.util.List<model.FnB> hasilPencarian = dao.searchByName(keyword);

        // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelfnb.getModel();
        model.setRowCount(0); // Kosongkan tabel dulu

        if (hasilPencarian.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        } else {
            for (model.FnB f : hasilPencarian) {
                Object[] baris = {
                    f.getIdItem(),
                    f.getNamaItem(),
                    f.getHarga(),
                    f.getIdVendor()
                };
                model.addRow(baris);
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        tampilkanData();
    }//GEN-LAST:event_viewActionPerformed

    private void tempatsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatsearchActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed

        String keyword = tempatsearch.getText();

        dao.FnbDao dao = new dao.FnbDao();

        // Panggil method SEARCH dari DAO
        java.util.List<model.FnB> hasilPencarian = dao.searchByName(keyword);

        // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelfnb.getModel();
        model.setRowCount(0); // Kosongkan tabel dulu

        if (hasilPencarian.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        } else {
            for (model.FnB f : hasilPencarian) {
                Object[] baris = {
                    f.getIdItem(),
                    f.getNamaItem(),
                    f.getHarga(),
                    f.getIdVendor()
                };
                model.addRow(baris);
            }
        }
    }//GEN-LAST:event_search1ActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        tampilkanDataFnb();
    }//GEN-LAST:event_view1ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        String keyword = tempatsearch.getText();

        dao.RuanganDao dao = new dao.RuanganDao();

        // Panggil method SEARCH dari DAO
        java.util.List<model.Ruangan> hasilPencarian = dao.searchByName(keyword);

        // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelruangan.getModel();
        model.setRowCount(0); // Kosongkan tabel dulu

        if (hasilPencarian.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        } else {
            for (model.Ruangan f : hasilPencarian) {
                Object[] baris = {
                    f.getIdRuangan(),
                    f.getNamaRuangan(),
                    f.getHargaPerJam()
                };
                model.addRow(baris);
            }
        }
    }//GEN-LAST:event_search2ActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        tampilkanData();
    }//GEN-LAST:event_view2ActionPerformed

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        String keyword = tempatsearch.getText();

        dao.RuanganDao dao = new dao.RuanganDao();

        // Panggil method SEARCH dari DAO
        java.util.List<model.Ruangan> hasilPencarian = dao.searchByName(keyword);

        // --- Masukkan hasil ke JTable (Logika mirip tampilkanData) ---
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelruangan.getModel();
        model.setRowCount(0); // Kosongkan tabel dulu

        if (hasilPencarian.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        } else {
            for (model.Ruangan f : hasilPencarian) {
                Object[] baris = {
                    f.getIdRuangan(),
                    f.getNamaRuangan(),
                    f.getHargaPerJam()
                };
                model.addRow(baris);
            }
        }
    }//GEN-LAST:event_search3ActionPerformed

    private void view3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view3ActionPerformed
        tampilkanData();
    }//GEN-LAST:event_view3ActionPerformed

    private void tempatsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatsearch1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int sel = tabelruangan.getSelectedRow();
        if (sel < 0) { 
            JOptionPane.showMessageDialog(this,"Pilih ruangan dulu"); 
            return; 
        }
        String idRuangan = tabelruangan.getValueAt(sel, 0).toString(); 
        String namaRuangan = tabelruangan.getValueAt(sel, 1).toString(); 
        double hargaPerJam = Double.parseDouble(tabelruangan.getValueAt(sel, 2).toString());

        // parse waktu mulai & selesai (format HH:mm)
        String sMulai = wmulai.getText().trim();
        String sSelesai = wselesai.getText().trim();

        if (sMulai.isEmpty() || sSelesai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi waktu mulai & selesai");
            return;
        }

        try {
            java.time.LocalTime mulai = java.time.LocalTime.parse(sMulai); 
            java.time.LocalTime selesai = java.time.LocalTime.parse(sSelesai);

            if (!selesai.isAfter(mulai)) { 
                JOptionPane.showMessageDialog(this, "Waktu selesai harus setelah mulai"); 
                return; 
            }

            java.time.Duration dur = java.time.Duration.between(mulai, selesai);
            long jam = dur.toHours();
            long menit = dur.toMinutesPart();

            // durasi string
            String durasiText = String.format("%dh %02dm", jam, menit);

            // hitung total jam (desimal)
            double totalJam = jam + (menit / 60.0);

            double subtotal = hargaPerJam * totalJam;

            // === Tambah ke tabel rekap (3 kolom saja) ===
            modelRekapRuangan.addRow(new Object[]{
                idRuangan,
                namaRuangan,
                sMulai,
                sSelesai,
                durasiText,
                subtotal
            });

            updateTotal();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Format waktu harus HH:mm (contoh 10:30)");
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void addfnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfnbActionPerformed
                               
    int sel = tabelfnb.getSelectedRow();
    if (sel < 0) { 
        JOptionPane.showMessageDialog(this,"Pilih item F&B dulu"); 
        return; 
    }
    String idItem = tabelfnb.getValueAt(sel, 0).toString();
    String namaItem = tabelfnb.getValueAt(sel, 1).toString();
    double harga = Double.parseDouble(tabelfnb.getValueAt(sel, 2).toString());

    // ambil qty
    int qty;
    try {
        qty = Integer.parseInt(tptqty.getText().trim());
        if (qty <= 0) throw new NumberFormatException();
    } catch (Exception e) { 
        JOptionPane.showMessageDialog(this,"Masukkan qty valid"); 
        return; 
    }

    // hitung subtotal
    double subtotal = harga * qty;

    // Tambahkan ke tabel rekap (nama, qty, subtotal)
    modelRekapFnb.addRow(new Object[]{
        idItem,
        namaItem,
        qty,
        subtotal
    });

    updateTotal();

    }//GEN-LAST:event_addfnbActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    int selR = rekapruangan.getSelectedRow();
    int selF = rekapfnb.getSelectedRow();
    if (selR >= 0) {
        modelRekapRuangan.removeRow(selR);
    } else if (selF >= 0) {
        modelRekapFnb.removeRow(selF);
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang mau dihapus di salah satu rekap table");
        return;
    }
    updateTotal();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void hitungsusukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungsusukActionPerformed
                                     
    try {
        double bayar = Double.parseDouble(tempatbayar.getText().trim());
        // parse lblTotal text "Rp 12345"
        String totText = tpttotal.getText().replaceAll("[^0-9.]", "");
        double total = totText.isEmpty() ? 0 : Double.parseDouble(totText);
        double kembali = bayar - total;
        kembalian.setText(String.format("Rp %.0f", kembali));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Masukkan nominal bayar yang valid");
}
    }//GEN-LAST:event_hitungsusukActionPerformed

    private void resetForm() {
    // 1. Kosongkan Text Field
    tnama.setText("");
    ttelp.setText("");
    tidtrans.setText("");
    token.setText("");
    tpttotal.setText(""); // Atau set ke "0"

    // 2. Kembalikan Pilihan ComboBox ke Awal (Index 0)
    if (kasircom.getItemCount() > 0) {
        kasircom.setSelectedIndex(0);
    }
    if (pmbyrn.getItemCount() > 0) {
        pmbyrn.setSelectedIndex(0);
    }

    // 3. Hapus Semua Baris di Tabel (Ruangan & FnB)
    modelRekapRuangan.setRowCount(0);
    modelRekapFnb.setRowCount(0);

    // 4. Fokuskan kursor kembali ke inputan pertama (Nama)
    tnama.requestFocus();
}
    
    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
                                        
    try {
        // ==========================================
        // BAGIAN 1: VALIDASI & INPUT DASAR (GAK DIUBAH)
        // ==========================================
        String namaPelanggan = tnama.getText().trim();
        String telp = ttelp.getText().trim();
        
        if (namaPelanggan.isEmpty()) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Isi nama pelanggan dulu"); 
            return; 
        }

        // Ambil ID Kasir & Pembayaran
        String idKasir = kasircom.getSelectedItem().toString().split(" - ")[0];
        String idPembayaran = pmbyrn.getSelectedItem().toString().split(" - ")[0];


        // ==========================================
        // BAGIAN 2: SIAPKAN DATA (PACKING KE DALAM LIST)
        // ==========================================
        // Disini kita cuma masukin data tabel ke List,
        // INSERT-nya nanti dilakukan otomatis oleh Service.
        
        // A. List Ruangan
        java.util.List<model.TransaksiRuangan> listRuangan = new java.util.ArrayList<>();
        for (int i = 0; i < modelRekapRuangan.getRowCount(); i++) {
            model.TransaksiRuangan tr = new model.TransaksiRuangan();
            tr.setIdRuangan(modelRekapRuangan.getValueAt(i, 0).toString());
            
            // Format waktu (tambah :00 biar jadi detik)
            String m = modelRekapRuangan.getValueAt(i, 2).toString() + ":00";
            String s = modelRekapRuangan.getValueAt(i, 3).toString() + ":00";
            tr.setWaktuMulai(java.sql.Time.valueOf(m));
            tr.setWaktuSelesai(java.sql.Time.valueOf(s));
            
            listRuangan.add(tr); 
        }

        // B. List FNB
        java.util.List<model.TransaksiFnb> listFnb = new java.util.ArrayList<>();
        for (int i = 0; i < modelRekapFnb.getRowCount(); i++) {
            model.TransaksiFnb tf = new model.TransaksiFnb();
            tf.setIdItem(modelRekapFnb.getValueAt(i, 0).toString());
            tf.setKuantitas(Integer.parseInt(modelRekapFnb.getValueAt(i, 2).toString()));
            
            listFnb.add(tf); 
        }


        // ==========================================
        // BAGIAN 3: PANGGIL SERVICE (EKSEKUSI INSERT)
        // ==========================================
        service.TransaksiService service = new service.TransaksiService();
        
        // Service akan: Panggil SP -> Insert List Ruangan -> Insert List FnB -> Commit
        dao.SPTransaksiDao.SpResult res = service.simpanTransaksiViaSP(
        namaPelanggan,
        telp,
        idKasir,
        idPembayaran,
        listRuangan,
        listFnb
        );
        
        // ==========================================
        // BAGIAN 4: TAMPILKAN HASIL & STRUK
        // ==========================================
        if (res != null) {
            // Kalau berhasil, ambil ID & Token baru
            String idTransaksi = res.idTransaksi;
            String tokenWifi = res.tokenWifi;

            tidtrans.setText(idTransaksi);
            token.setText(tokenWifi);

            // Hitung Total (Function)
            dao.FNPerhitunganDao fndao = new dao.FNPerhitunganDao(util.DatabaseConnection.getConnection());
            double total = fndao.hitungTotalBelanja(idTransaksi);
            tpttotal.setText("Rp " + total);
            
            // --- GENERATE STRUK ---
            StringBuilder sb = new StringBuilder();

            sb.append("========= STRUK DAGO SPACE =========\n");
            sb.append("ID Transaksi : ").append(idTransaksi).append("\n");
            sb.append("Kasir        : ").append(kasircom.getSelectedItem()).append("\n");
            sb.append("Pelanggan    : ").append(namaPelanggan).append("\n");
            sb.append("Telepon      : ").append(telp).append("\n");
            sb.append("Token WiFi   : ").append(tokenWifi).append("\n\n");

            sb.append("------ Detail Ruangan ------\n");
            for (int i = 0; i < modelRekapRuangan.getRowCount(); i++) {
                sb.append(modelRekapRuangan.getValueAt(i, 1))      // nama ruangan
                  .append(" | ")
                  .append(modelRekapRuangan.getValueAt(i, 4))      // Durasi
                  .append(" |Rp ")
                  .append(modelRekapRuangan.getValueAt(i, 5))      // subtotal
                  .append(" | \n");
            }

            sb.append("\n------ Detail F&B ------\n");
            for (int i = 0; i < modelRekapFnb.getRowCount(); i++) {
                sb.append(modelRekapFnb.getValueAt(i, 1))         // nama item
                  .append(" x ")
                  .append(modelRekapFnb.getValueAt(i, 2))         // qty
                  .append(" |Rp ")
                  .append(modelRekapFnb.getValueAt(i, 3))         // subtotal
                  .append("| \n");
            }

            sb.append("\nTotal Bayar : Rp ").append(total).append("\n");
            sb.append("=====================================");

            String STRUK_FINAL = sb.toString();

            // Tampilkan Popup
            javax.swing.JOptionPane.showMessageDialog(this,
                STRUK_FINAL,
                "Struk Transaksi",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Bersihkan Layar
            resetForm();
            
        } else {
            // Kalau Service gagal (Rollback otomatis)
            javax.swing.JOptionPane.showMessageDialog(this, "Maaf, Transaksi gagal!");
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal proses transaksi: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_prosesActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MainMenu mnu = new MainMenu();
        mnu.setVisible(true);

        // TUTUP Vendor
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tampilkanData() {
    // 1. Siapkan Model Tabel
    // Pastikan nama variabel tabelmu sesuai (misal: jTable1 atau tblData)
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelruangan.getModel();
    
    // 2. Kosongkan tabel dulu agar tidak dobel saat direfresh
    model.setRowCount(0);

    // 3. Ambil data dari Database pakai DAO
    dao.RuanganDao dao = new dao.RuanganDao();
    java.util.List<model.Ruangan> ListRuangan = dao.getAll();

    // 4. Masukkan data ke Tabel
    for (model.Ruangan f : ListRuangan) {
        Object[] baris = {
            f.getIdRuangan(),
            f.getNamaRuangan(),
            f.getHargaPerJam()
            // Tambahkan nama vendor jika ada di model
        };
        model.addRow(baris);
    }
}

private void tampilkanDataFnb() {
    // 1. Siapkan Model Tabel
    // Pastikan nama variabel tabelmu sesuai (misal: jTable1 atau tblData)
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelfnb.getModel();
    
    // 2. Kosongkan tabel dulu agar tidak dobel saat direfresh
    model.setRowCount(0);

    // 3. Ambil data dari Database pakai DAO
    dao.FnbDao dao = new dao.FnbDao();
    java.util.List<model.FnB> listFnb = dao.getAll();

    // 4. Masukkan data ke Tabel
    for (model.FnB f : listFnb) {
        Object[] baris = {
            f.getIdItem(),
            f.getNamaItem(),
            f.getHarga(),
            f.getIdVendor()
            // Tambahkan nama vendor jika ada di model
        };
        model.addRow(baris);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfnb;
    private javax.swing.JButton hitungsusuk;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> kasircom;
    private javax.swing.JTextArea kembalian;
    private javax.swing.JComboBox<String> pmbyrn;
    private javax.swing.JButton proses;
    private javax.swing.JTable rekapfnb;
    private javax.swing.JTable rekapruangan;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JButton search2;
    private javax.swing.JButton search3;
    private javax.swing.JTable tabelfnb;
    private javax.swing.JTable tabelruangan;
    private javax.swing.JTextField tempatbayar;
    private javax.swing.JTextField tempatsearch;
    private javax.swing.JTextField tempatsearch1;
    private javax.swing.JTextField tidtrans;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField token;
    private javax.swing.JTextField tptqty;
    private javax.swing.JTextArea tpttotal;
    private javax.swing.JTextField ttelp;
    private com.toedter.calendar.JDateChooser ttgl;
    private javax.swing.JButton view;
    private javax.swing.JButton view1;
    private javax.swing.JButton view2;
    private javax.swing.JButton view3;
    private javax.swing.JTextField wmulai;
    private javax.swing.JTextField wselesai;
    // End of variables declaration//GEN-END:variables
}